<?php

require_once __DIR__ . '/vendor/autoload.php';

use gold\GoldPortSecondClient\Application;
use gold\GoldPortSecondService\AccountReleaseService;
use gold\GoldPortSecondService\AcrossBillService;
use gold\GoldPortSecondService\DeclareRecordService;
use gold\GoldPortSecondService\NuclearNoteService;

$ioc_con_app = new Application();

// $test = new DeclareRecordService($ioc_con_app);

// $declareConfig = [
//     'message_id'           => 'SAS121_20190706104235248',
//     'file_name'           => 'SAS121_20190706104235248',
//     'sender_id'           => '123',
//     'receiver_id'           => '123',
//     'OperCusRegCode'           => '操作卡海关十位代码',
//     'DelcareFlag'           => '申报标志(0-暂存、1-申报)',
// ];

// $declareParams = [
//     'appHeadType'=> [
//         [
//             'SeqNo'=> '预录入统一编号',
//             'SasDclNo'=> '申报表编号',
//             'MaserCuscd'=> '主管关区代码',
//             'DclTypecd'=> '申报类型代码',
//             'BusinessTypecd'=> '业务类型代码',
//             'DirectionTypecd'=> '货物流向代码',
//             'AreainOriactNo'=> '区内账册编号',
//             'AreaoutOriactNo'=> '区外账册编号',
//             'AreainEtpsno'=> '区内企业编码',
//             'AreainEtpsNm'=> '区内企业名称',
//             'AreainEtpsSccd'=> '区内企业社会信用代码',
//             'AreaoutEtpsno'=> '区外企业编码',
//             'AreaoutEtpsNm'=> '区外企业名称',
//             'AreaoutEtpsSccd'=> '区外企业社会信用代码',
//             'ValidTime'=> '有效期',
//             'DclEr'=> '申请人',
//             'DclEtpsno'=> '申报企业编号',
//             'DclEtpsNm'=> '申报企业名称',
//             'DclEtpsSccd'=> '申报企业社会信用代码',
//             'InputCode'=> '录入单位代码',
//             'InputSccd'=> '录入单位社会信用代码',
//             'InputName'=> '录入单位名称',
//             'EtpsPreentNo'=> '企业内部编号',
//             'MtpckEndprdTypecd'=> '底账料件成品标志',
//             'FreeDomestic'=> '保税区内销标志，“Y”：是，默认为空',
//         ],
//         [
//             'SeqNo'=> '预录入统一编号',
//             'SasDclNo'=> '申报表编号',
//             'MaserCuscd'=> '主管关区代码',
//             'DclTypecd'=> '申报类型代码',
//             'BusinessTypecd'=> '业务类型代码',
//             'DirectionTypecd'=> '货物流向代码',
//             'AreainOriactNo'=> '区内账册编号',
//             'AreaoutOriactNo'=> '区外账册编号',
//             'AreainEtpsno'=> '区内企业编码',
//             'AreainEtpsNm'=> '区内企业名称',
//             'AreainEtpsSccd'=> '区内企业社会信用代码',
//             'AreaoutEtpsno'=> '区外企业编码',
//             'AreaoutEtpsNm'=> '区外企业名称',
//             'AreaoutEtpsSccd'=> '区外企业社会信用代码',
//             'ValidTime'=> '有效期',
//             'DclEr'=> '申请人',
//             'DclEtpsno'=> '申报企业编号',
//             'DclEtpsNm'=> '申报企业名称',
//             'DclEtpsSccd'=> '申报企业社会信用代码',
//             'InputCode'=> '录入单位代码',
//             'InputSccd'=> '录入单位社会信用代码',
//             'InputName'=> '录入单位名称',
//             'EtpsPreentNo'=> '企业内部编号',
//             'MtpckEndprdTypecd'=> '底账料件成品标志',
//             'FreeDomestic'=> '保税区内销标志，“Y”：是，默认为空',
//         ],
//     ],

//     'appGoodsType'=> [
//         [
//             'SeqNo' => '预录入编号',
//             'SasDclNo' => '申报表编号',
//             'SasDclSeqno' => '申报序号',
//             'OriactGdsSeqno' => '底账商品序号',
//             'MtpckEndprdTypecd' => '料件成品标志代码',
//             'Gdecd' => '商品编码',
//             'GdsNm' => '商品名称',
//             'GdsSpcfModelDesc' => '商品规格型号描述',
//             'DclQty' => '数量',
//             'DclUnitcd' => '申报计量单位代码',
//             'DclUprcAmt' => '单价',
//             'DclTotalAmt' => '总价',
//             'DclCurrcd' => '币制代码',
//             'LicenceVaildTime' => '许可证有效期',
//             'GdsMarkcd' => '商品标记代码',
//             'ModfMarkcd' => '修改标志代码',
//             'GdsMtno' => '商品料号',
//             'LawfUnitcd' => '法定计量单位代码',
//             'SecdLawfUnitcd' => '法定第二计量单位代码',

//         ],
//         [
//             'SeqNo' => '预录入编号',
//             'SasDclNo' => '申报表编号',
//             'SasDclSeqno' => '申报序号',
//             'OriactGdsSeqno' => '底账商品序号',
//             'MtpckEndprdTypecd' => '料件成品标志代码',
//             'Gdecd' => '商品编码',
//             'GdsNm' => '商品名称',
//             'GdsSpcfModelDesc' => '商品规格型号描述',
//             'DclQty' => '数量',
//             'DclUnitcd' => '申报计量单位代码',
//             'DclUprcAmt' => '单价',
//             'DclTotalAmt' => '总价',
//             'DclCurrcd' => '币制代码',
//             'LicenceVaildTime' => '许可证有效期',
//             'GdsMarkcd' => '商品标记代码',
//             'ModfMarkcd' => '修改标志代码',
//             'GdsMtno' => '商品料号',
//             'LawfUnitcd' => '法定计量单位代码',
//             'SecdLawfUnitcd' => '法定第二计量单位代码',

//         ],
//     ],

// ];

// var_dump($test->getDeclareRecordXml($declareConfig,$declareParams));
// die();

// **********-------------------------------------------------------------
// 出入库单-------------------------------------------------------------
// **********-------------------------------------------------------------

// $declareConfig = [
//     'business_id'           => 'SAS121_20190706104235248',
//     'message_id'           => 'SAS121_20190706104235248',
//     'file_name'           => 'SAS121_20190706104235248',
//     'sender_id'           => '123',
//     'receiver_id'           => '123',
//     'OperCusRegCode'           => '操作卡海关十位代码',
//     'DelcareFlag'           => '申报标志(0-暂存、1-申报)',
//     'Ic_Card'           => '123',
//     // 'IsUnstructured'           => '123',

// ];

// $declareParams = [
//     'appHeadType'=> [
//         [
//             'SeqNo' => '',
//             'DclTypecd' => '申报类型代码',
//             'SasDclNo' => '出入库单编号',
//             'AreainOriactNo' => '区内账册编号',
//             'AreainEtpsNo' => '区内企业编码',
//             'AreainEtpsNm' => '区内企业名称',
//             'AreainEtpsSccd' =>'区内企业社会信用代码',
//             'MasterCuscd' => '主管关区',
//             'StockTypecd' => '出入库类型',
//             'BusinessTypecd' => '业务类型',
//             'DclEr' => '申请人',
//             'DclEtpsNo' => '申报单位编码',
//             'DclEtpsNm' => '申报单位名称',
//             'DclEtpsSccd' => '申报单位社会信用代码',
//             'InputCode' => '录入单位编码',
//             'InputSccd' => '录入单位社会信用代码',
//             'InputName' => '录入单位名称',
//             'EtpsPreentNo' => '企业内部编号',
//             'PackageQty' => '件数',
//             'GrossWt' => '毛重',
//             'NetWt' =>'净重',
//             'PackType' => '包装种类',
//             'InputDate' => '录入日期',
//             'MtpckEndprdTypecd' => '底账料件成品标志',
//         ],
//         [
//             'SeqNo' => '',
//             'DclTypecd' => '申报类型代码',
//             'SasDclNo' => '出入库单编号',
//             'AreainOriactNo' => '区内账册编号',
//             'AreainEtpsNo' => '区内企业编码',
//             'AreainEtpsNm' => '区内企业名称',
//             'AreainEtpsSccd' =>'区内企业社会信用代码',
//             'MasterCuscd' => '主管关区',
//             'StockTypecd' => '出入库类型',
//             'BusinessTypecd' => '业务类型',
//             'DclEr' => '申请人',
//             'DclEtpsNo' => '申报单位编码',
//             'DclEtpsNm' => '申报单位名称',
//             'DclEtpsSccd' => '申报单位社会信用代码',
//             'InputCode' => '录入单位编码',
//             'InputSccd' => '录入单位社会信用代码',
//             'InputName' => '录入单位名称',
//             'EtpsPreentNo' => '企业内部编号',
//             'PackageQty' => '件数',
//             'GrossWt' => '毛重',
//             'NetWt' =>'净重',
//             'PackType' => '包装种类',
//             'InputDate' => '录入日期',
//             'MtpckEndprdTypecd' => '底账料件成品标志',
//         ],
//     ],

//     'appGoodsType'=> [
//         [
//             'SeqNo' => 'max:18',
//             'SasStockSeqno' => '商品序号',
//             'SasDclSeqno' => '申报表序号',
//             'OriactGdsSeqno' => '备案序号',
//             'GdsMtno' => '商品料号',
//             'Gdecd' => '商品编码',
//             'GdsNm' => '商品名称',
//             'GdsSpcfModelDesc' => '商品规格型号',
//             'DclUnitcd' => '申报计量单位代码',
//             'LawfUnitcd' => '法定计量单位代码',
//             'Natcd' => '国别代码',
//             'DclUprcAmt' => '申报单价',
//             'DclTotalAmt' => '申报总价',
//             'DclCurrcd' => '申报币制代码',
//             'LawfQty' => '法定数量',
//             'WtSfVal' => '重量比例因子',
//             'FstSfVal' => '第一比例因子',
//             'SecdSfVal' => '第二比例因子',
//             'DclQty' => '申报数量',
//             'GrossWt' => '毛重',
//             'NetWt' => '净重',
//             'LvyrlfModecd' => '征免方式代码',
//             'UcnsVerno' => '单耗版本号',
//             'RltGdsSeqno' => '关联商品序号',
//             'DestinationNatcd' => '最终目的国',
//             'ModfMarcked' => '修改标志',

//     ],
//     [
//         'SeqNo' => 'max:18',
//         'SasStockSeqno' => '商品序号',
//         'SasDclSeqno' => '申报表序号',
//         'OriactGdsSeqno' => '备案序号',
//         'GdsMtno' => '商品料号',
//         'Gdecd' => '商品编码',
//         'GdsNm' => '商品名称',
//         'GdsSpcfModelDesc' => '商品规格型号',
//         'DclUnitcd' => '申报计量单位代码',
//         'LawfUnitcd' => '法定计量单位代码',
//         'Natcd' => '国别代码',
//         'DclUprcAmt' => '申报单价',
//         'DclTotalAmt' => '申报总价',
//         'DclCurrcd' => '申报币制代码',
//         'LawfQty' => '法定数量',
//         'WtSfVal' => '重量比例因子',
//         'FstSfVal' => '第一比例因子',
//         'SecdSfVal' => '第二比例因子',
//         'DclQty' => '申报数量',
//         'GrossWt' => '毛重',
//         'NetWt' => '净重',
//         'LvyrlfModecd' => '征免方式代码',
//         'UcnsVerno' => '单耗版本号',
//         'RltGdsSeqno' => '关联商品序号',
//         'DestinationNatcd' => '最终目的国',
//         'ModfMarcked' => '修改标志',

// ],
//     ],
//     'pocketInfo'=> [
//         'is_unstructured'         => '4',
//     ],

// ];
// $test = new AcrossBillService($ioc_con_app);
// var_dump($test->getAcrossBillXml($declareConfig,$declareParams));
// die();

//**********-------------------------------------------------------------
//核放单-------------------------------------------------------------
//**********-------------------------------------------------------------

$declareConfig = [
    'message_id'     => 'SAS121_20190706104235248',
    'file_name'      => 'SAS121_20190706104235248',
    'sender_id'      => '123',
    'receiver_id'    => '123',
    'OperCusRegCode' => '操作卡海关十位代码',
    'DelcareFlag'    => '申报标志(0-暂存、1-申报)',
    'Ic_Card'        => '123',
    // 'IsUnstructured'           => '123',
];

$declareParams = [
    'appHeadType' => [
        [
            'SeqNo'          => 'wwww',
            'PassportNo'     => 'wwww',
            'PassportTypecd' => 'wwww',
            'MasterCuscd'    => 'wwww',
            'DclTypecd'      => 'wwww',
            'IoTypecd'       => 'wwww',
            'BindTypecd'     => 'wwww',
            'RltTbTypecd'    => 'wwww',
            'RltNo'          => 'wwww',
            'AreainOriactNo' => 'wwww',
            'AreainEtpsno'   => 'wwww',
            'AreainEtpsNm'   => 'wwww',
            'AreainEtpsSccd' => 'wwww',
            'VehicleNo'      => 'wwww',
            'VehicleIcNo'    => 'wwww',
            'ContainerNo'    => 'wwww',
            'VehicleWt'      => 'wwww',
            'VehicleFrameNo' => 'wwww',
            'VehicleFrameWt' => 'wwww',
            'ContainerType'  => 'wwww',
            'ContainerWt'    => 'wwww',
            'TotalWt'        => 'wwww',
            'TotalGrossWt'   => 'wwww',
            'TotalNetWt'     => 'wwww',
            'DclErConc'      => 'wwww',
            'DclTime'        => 'wwww',
            'DclEtpsno'      => 'wwww',
            'DclEtpsNm'      => 'wwww',
            'DclEtpsSccd'    => 'wwww',
            'InputCode'      => 'wwww',
            'InputSccd'      => 'wwww',
            'InputName'      => 'wwww',
            'EtpsPreentNo'   => 'wwww',
            'Rmk'            => 'wwww',
            'Col1'           => 'wwww',
        ],
        [
            'SeqNo'          => 'wwww',
            'PassportNo'     => 'wwww',
            'PassportTypecd' => 'wwww',
            'MasterCuscd'    => 'wwww',
            'DclTypecd'      => 'wwww',
            'IoTypecd'       => 'wwww',
            'BindTypecd'     => 'wwww',
            'RltTbTypecd'    => 'wwww',
            'RltNo'          => 'wwww',
            'AreainOriactNo' => 'wwww',
            'AreainEtpsno'   => 'wwww',
            'AreainEtpsNm'   => 'wwww',
            'AreainEtpsSccd' => 'wwww',
            'VehicleNo'      => 'wwww',
            'VehicleIcNo'    => 'wwww',
            'ContainerNo'    => 'wwww',
            'VehicleWt'      => 'wwww',
            'VehicleFrameNo' => 'wwww',
            'VehicleFrameWt' => 'wwww',
            'ContainerType'  => 'wwww',
            'ContainerWt'    => 'wwww',
            'TotalWt'        => 'wwww',
            'TotalGrossWt'   => 'wwww',
            'TotalNetWt'     => 'wwww',
            'DclErConc'      => 'wwww',
            'DclTime'        => 'wwww',
            'DclEtpsno'      => 'wwww',
            'DclEtpsNm'      => 'wwww',
            'DclEtpsSccd'    => 'wwww',
            'InputCode'      => 'wwww',
            'InputSccd'      => 'wwww',
            'InputName'      => 'wwww',
            'EtpsPreentNo'   => 'wwww',
            'Rmk'            => 'wwww',
            'Col1'           => 'wwww',
        ],
    ],

    'passport' => [
        [
            'SeqNo'         => '1',
            'PassPortNo'    => '2',
            'RtlBillTypecd' => '3',
            'RtlBillNo'     => '4',
        ],
        [
            'SeqNo'         => '1',
            'PassPortNo'    => '2',
            'RtlBillTypecd' => '3',
            'RtlBillNo'     => '4',
        ],
    ],

    'pocketInfo' => [
        'pocket_id'        => '1',
        'total_pocket_qty' => '2',
        'cur_pocket_no'    => '3',
        'is_unstructured'  => '4',
    ],
];
$test = new AccountReleaseService($ioc_con_app);
var_dump($test->getAccountReleaseXml($declareConfig, $declareParams));
die();

//**********-------------------------------------------------------------
//核注清单-------------------------------------------------------------
//**********-------------------------------------------------------------

$declareConfig = [
    'message_id'     => 'SAS121_20190706104235248',
    'file_name'      => 'SAS121_20190706104235248',
    'sender_id'      => '123',
    'receiver_id'    => '123',
    'OperCusRegCode' => '操作卡海关十位代码',
    'DelcareFlag'    => '申报标志(0-暂存、1-申报)',
    'Ic_Card'        => '123',
    // 'IsUnstructured'           => '123',
    'SysId' => '12',
];

$declareParams = [
    'HeadType' => [
        [
            'SeqNo'                  => 'max:18',
            'BondInvtNo'             => 'max:64',
            'ChgTmsCnt'              => 'require|max:64',
            'PutrecNo'               => 'require|max:64',
            'InvtType'               => 'require|in:0,1,2,3,4,5,6,7,8,9',
            'EtpsInnerInvtNo'        => 'max:64',
            'BizopEtpsno'            => 'require|max:10',
            'BizopEtpsSccd'          => 'max:18',
            'BizopEtpsNm'            => 'require|max:512',
            'RcvgdEtpsno'            => 'require|max:18',
            'RvsngdEtpsSccd'         => 'max:18',
            'RcvgdEtpsNm'            => 'require|max:512',
            'DclEtpsno'              => 'require|max:10',
            'DclEtpsSccd'            => 'max:18',
            'DclEtpsNm'              => 'require|max:512',
            'InputCode'              => 'require|max:10',
            'InputCreditCode'        => 'max:18',
            'InputName'              => 'require|max:255',
            'InputTime'              => 'max:8',
            'RltInvtNo'              => 'max:64',
            'RltPutrecNo'            => 'max:64',
            'CorrEntryDclEtpsNo'     => 'max:10',
            'CorrEntryDclEtpsSccd'   => 'max:18',
            'CorrEntryDclEtpsNm'     => 'max:512',
            'RltEntryBizopEtpsno'    => 'max:10',
            'RltEntryBizopEtpsSccd'  => 'max:18',
            'RltEntryBizopEtpsNm'    => 'max:512',
            'RltEntryRcvgdEtpsno'    => 'max:10',
            'RltEntryRvsngdEtpsSccd' => 'max:18',
            'RltEntryRcvgdEtpsNm'    => 'max:512',
            'RltEntryDclEtpsno'      => 'max:10',
            'RltEntryDclEtpsSccd'    => 'max:18',
            'RltEntryDclEtpsNm'      => 'max:512',
            'ImpexpPortcd'           => 'require|max:4',
            'DclPlcCuscd'            => 'require|max:4',
            'ImpexpMarkcd'           => 'require|max:4|in:I,E',
            'MtpckEndprdMarkcd'      => 'require|max:4|in:I,E',
            'SupvModecd'             => 'require|max:6',
            'TrspModecd'             => 'require|max:6',
            'ApplyNo'                => 'max:64',
            'ListType'               => 'require|max:1',
            'DclcusFlag'             => 'require|max:1|in:1,2',
            'DclcusTypecd'           => 'max:25',
            'IcCardNo'               => 'max:20',
            'DecType'                => 'require|max:1',
            'Rmk'                    => 'max:4000',
            'StshipTrsarvNatcd'      => 'require|max:3',
            'EntryNo'                => 'max:64',
            'RltEntryNo'             => 'max:64',
            'DclTypecd'              => 'require|max:1|in:1,2,3',
            'InvtDclTime'            => 'max:18',
            'EntryDclTime'           => 'max:18',
            'VrfdedMarkcd'           => 'max:4',
            'InvtIochkptStucd'       => 'max:4',
            'PrevdTime'              => 'max:18',
            'FormalVrfdedTime'       => 'max:18',
            'EntryStucd'             => 'max:1',
            'PassportUsedTypeCd'     => 'max:1',
            'NeedEntryModified'      => 'max:1',
            'LevyBlAmt'              => 'max:25',
            'GenDecFlag'             => 'require|max:2|in:1,2',
        ],
        [
            'SeqNo'                  => 'max:18',
            'BondInvtNo'             => 'max:64',
            'ChgTmsCnt'              => 'require|max:64',
            'PutrecNo'               => 'require|max:64',
            'InvtType'               => 'require|in:0,1,2,3,4,5,6,7,8,9',
            'EtpsInnerInvtNo'        => 'max:64',
            'BizopEtpsno'            => 'require|max:10',
            'BizopEtpsSccd'          => 'max:18',
            'BizopEtpsNm'            => 'require|max:512',
            'RcvgdEtpsno'            => 'require|max:18',
            'RvsngdEtpsSccd'         => 'max:18',
            'RcvgdEtpsNm'            => 'require|max:512',
            'DclEtpsno'              => 'require|max:10',
            'DclEtpsSccd'            => 'max:18',
            'DclEtpsNm'              => 'require|max:512',
            'InputCode'              => 'require|max:10',
            'InputCreditCode'        => 'max:18',
            'InputName'              => 'require|max:255',
            'InputTime'              => 'max:8',
            'RltInvtNo'              => 'max:64',
            'RltPutrecNo'            => 'max:64',
            'CorrEntryDclEtpsNo'     => 'max:10',
            'CorrEntryDclEtpsSccd'   => 'max:18',
            'CorrEntryDclEtpsNm'     => 'max:512',
            'RltEntryBizopEtpsno'    => 'max:10',
            'RltEntryBizopEtpsSccd'  => 'max:18',
            'RltEntryBizopEtpsNm'    => 'max:512',
            'RltEntryRcvgdEtpsno'    => 'max:10',
            'RltEntryRvsngdEtpsSccd' => 'max:18',
            'RltEntryRcvgdEtpsNm'    => 'max:512',
            'RltEntryDclEtpsno'      => 'max:10',
            'RltEntryDclEtpsSccd'    => 'max:18',
            'RltEntryDclEtpsNm'      => 'max:512',
            'ImpexpPortcd'           => 'require|max:4',
            'DclPlcCuscd'            => 'require|max:4',
            'ImpexpMarkcd'           => 'require|max:4|in:I,E',
            'MtpckEndprdMarkcd'      => 'require|max:4|in:I,E',
            'SupvModecd'             => 'require|max:6',
            'TrspModecd'             => 'require|max:6',
            'ApplyNo'                => 'max:64',
            'ListType'               => 'require|max:1',
            'DclcusFlag'             => 'require|max:1|in:1,2',
            'DclcusTypecd'           => 'max:25',
            'IcCardNo'               => 'max:20',
            'DecType'                => 'require|max:1',
            'Rmk'                    => 'max:4000',
            'StshipTrsarvNatcd'      => 'require|max:3',
            'EntryNo'                => 'max:64',
            'RltEntryNo'             => 'max:64',
            'DclTypecd'              => 'require|max:1|in:1,2,3',
            'InvtDclTime'            => 'max:18',
            'EntryDclTime'           => 'max:18',
            'VrfdedMarkcd'           => 'max:4',
            'InvtIochkptStucd'       => 'max:4',
            'PrevdTime'              => 'max:18',
            'FormalVrfdedTime'       => 'max:18',
            'EntryStucd'             => 'max:1',
            'PassportUsedTypeCd'     => 'max:1',
            'NeedEntryModified'      => 'max:1',
            'LevyBlAmt'              => 'max:25',
            'GenDecFlag'             => 'require|max:2|in:1,2',
        ],
    ],

    'list' => [
        [
            'SeqNo'            => 'max:18',
            'GdsSeqno'         => 'require|max:19',
            'PutrecSeqno'      => 'require|max:19',
            'GdsMtno'          => 'require|max:32',
            'Gdecd'            => 'require|max:10',
            'GdsNm'            => 'require|max:512',
            'GdsSpcfModelDesc' => 'require|max:255',
            'DclUnitcd'        => 'require|max:3',
            'LawfUnitcd'       => 'max:3',
            'SecdLawfUnitcd'   => 'max:3',
            'Natcd'            => 'require|max:3',
            'DclUprcAmt'       => 'require|max:19',
            'DclTotalAmt'      => 'require|max:19',
            'UsdStatTotalAmt'  => 'require|max:25',
            'DclCurrcd'        => 'require|max:3',
            'LawfQty'          => 'require|max:19',
            'SecdLawfQty'      => 'require|max:19',
            'WtSfVal'          => 'max:19',
            'FstSfVal'         => 'max:19',
            'SecdSfVal'        => 'max:19',
            'DclQt'            => 'require|max:19',
            'GrossWt'          => 'max:19',
            'NetWt'            => 'max:19',
            'LvyrlfModecd'     => 'require|max:6',
            'UcnsVerno'        => 'max:8',
            'ClyMarkcd'        => 'max:4',
            'EntryGdsSeqno'    => 'max:19',
            'ApplyTbSeqno'     => 'max:19',
            'DestinationNatcd' => 'require|max:3',
            'ModfMarkcd'       => 'require|max:1|in:0,1,2,3',
            'Rmk'              => 'max:4000',
        ],
        [
            'SeqNo'            => 'max:18',
            'GdsSeqno'         => 'require|max:19',
            'PutrecSeqno'      => 'require|max:19',
            'GdsMtno'          => 'require|max:32',
            'Gdecd'            => 'require|max:10',
            'GdsNm'            => 'require|max:512',
            'GdsSpcfModelDesc' => 'require|max:255',
            'DclUnitcd'        => 'require|max:3',
            'LawfUnitcd'       => 'max:3',
            'SecdLawfUnitcd'   => 'max:3',
            'Natcd'            => 'require|max:3',
            'DclUprcAmt'       => 'require|max:19',
            'DclTotalAmt'      => 'require|max:19',
            'UsdStatTotalAmt'  => 'require|max:25',
            'DclCurrcd'        => 'require|max:3',
            'LawfQty'          => 'require|max:19',
            'SecdLawfQty'      => 'require|max:19',
            'WtSfVal'          => 'max:19',
            'FstSfVal'         => 'max:19',
            'SecdSfVal'        => 'max:19',
            'DclQt'            => 'require|max:19',
            'GrossWt'          => 'max:19',
            'NetWt'            => 'max:19',
            'LvyrlfModecd'     => 'require|max:6',
            'UcnsVerno'        => 'max:8',
            'ClyMarkcd'        => 'max:4',
            'EntryGdsSeqno'    => 'max:19',
            'ApplyTbSeqno'     => 'max:19',
            'DestinationNatcd' => 'require|max:3',
            'ModfMarkcd'       => 'require|max:1|in:0,1,2,3',
            'Rmk'              => 'max:4000',
        ],
    ],

    'pocketInfo' => [
        'pocket_id'        => '1',
        'total_pocket_qty' => '2',
        'cur_pocket_no'    => '3',
        'is_unstructured'  => '4',
    ],
];
$test = new NuclearNoteService($ioc_con_app);
var_dump($test->getNuclearNoteXml($declareConfig, $declareParams));
die();
